Add basic documentation
omnivector-solutions/license-manager-simulator pull request #12
Opened 2021-09-13 14:51 UTC by zsinx6

- Add docstrings
- Improve use of LicenseNotFound exception
- Update README

2021-09-13 17:45 UTC, heitorPB commented on README.md
> +
```suggestion
You can add/remove Licenses from the license-server using the online interface at `http://localhost:8000/docs`. This helps you to make requests directly with the browser into the API, with examples.
```

2021-09-13 17:45 UTC, heitorPB commented on README.md
> +`license_manager_simulator/template_files` folder, there is the `lms-util.py` file. To be able to use
```suggestion
`license_manager_simulator/template_files` folder, in there is the `lms-util.py` file. To be able to use
```

2021-09-13 17:48 UTC, heitorPB commented on README.md
> +`user$RANDOM` respectively.
```suggestion
We also have the `application.sh` script in the root of the repository, it is a simple bash script
that is intended to run in Slurm as a job that uses the licenses from the API. It is just a dummy
application for test that creates a license_in_use in the API, sleeps, then deletes the
license_in_use.

To run it, execute `./application.sh`. It is possible to specify the number of licenses as the first
argument and the user name as the second (e.g. `./application.sh 123 john_doe`), but they are 
optional and defaults to `42` and `user$RANDOM` respectively.
```

2021-09-13 19:16 UTC, heitorPB commented on README.md
> +
```suggestion
```

2021-09-13 19:16 UTC, heitorPB commented on README.md
> +
```suggestion
```

2021-09-13 19:18 UTC, heitorPB commented on tests/test_main.py
> +    assert "don't exists" in response.text
Is this correct? Shouldn't it be `don't exist`?

2021-09-14 04:09 UTC, zsinx6 commented on tests/test_main.py
> +    assert "don't exists" in response.text
I'm not sure, is the same as here: https://github.com/omnivector-solutions/license-manager-simulator/pull/12/files/51824ac14ad262e5d3d724a28b5a21e623fb7955#diff-af545a51f2130c56312be568a620b6ac2061bb7a3f7aec1cc572480019ba7e84R56

Should I change to `exist`?

2021-09-14 14:10 UTC, heitorPB requested changes
typos

2021-09-14 14:10 UTC, heitorPB commented on tests/test_main.py
> +    assert "doesn't exists" in response.text
```suggestion
    assert "doesn't exist" in response.text
```

2021-09-14 14:10 UTC, heitorPB commented on license_manager_simulator/main.py
> +            detail=f"The license {license_in_use.license_name} doesn't exists.",
```suggestion
            detail=f"The license {license_in_use.license_name} doesn't exist.",
```

2021-09-14 14:10 UTC, heitorPB commented on job/application.sh
> +          \"license_name\": \"fake_license.fake_feature\"}"
```suggestion
          \"user_name\": \""$USER"\", \
          \"lead_host\": \"$(hostname)\", \
          \"license_name\": \"fake_license.fake_feature\"}"
```

2021-09-14 15:03 UTC, heitorPB approved these changes

2021-09-14 16:41 UTC, jamesbeedy commented on README.md
> +This will run the server at `http://localhost:8000`
will the externally executed application.sh  be able to communicate with the simulator api when it listens on `localhost`? is there some way to make it listen on an ip that can be accessed over the network?

2021-09-14 16:47 UTC, jamesbeedy commented on job/application.sh
> +# change the URL
```suggestion
# You must modify this value to correctly reflect the ip address and port that the
# license-manager-simulator is listening on in your environment.
#
# The format of the value is: `http://<ip-address>:<port>`
```

2021-09-14 16:48 UTC, jamesbeedy commented on bin/lms-util.py
> +# Change this URL
```suggestion
# You must modify this value to reflect the ip address and port that the
# license-manager-simulator is listening on in your environment.
#
# The format of the value is: `http://<ip-address>:<port>`
```

2021-09-14 16:48 UTC, jamesbeedy commented on job/application.sh
> +          \"license_name\": \"fake_feature\"}"
Should this be `fake_product.fake_feature` ?

2021-09-14 16:50 UTC, zsinx6 commented on job/application.sh
> +          \"license_name\": \"fake_feature\"}"
Must be fake_feature

2021-09-14 16:56 UTC, jamesbeedy commented on tests/test_main.py
>          json={"license_name": "test_name", "quantity": 1, "user_name": "user1", "lead_host": "host1"},
```suggestion
        json={"license_name": "test_name", "quantity": 1, "user_name": "user1", "lead_host": "host1"},
```

Does this need to match the format `<product>.<feature>`?

2021-09-14 19:25 UTC, jamesbeedy commented on license_manager_simulator/crud.py
> +    """Creates the license_in_use.
```suggestion
    """Create the license_in_use.
```

2021-09-14 19:48 UTC, zsinx6 commented on tests/test_main.py
>          json={"license_name": "test_name", "quantity": 1, "user_name": "user1", "lead_host": "host1"},
No, just the feature

2021-09-14 19:49 UTC, zsinx6 commented on README.md
> +This will run the server at `http://localhost:8000`
Yes, the "localhost" just need to be reachable by the node

2021-09-14 19:56 UTC, jamesbeedy approved these changes
👍

2021-09-15 13:46 UTC, merged