Add docker-compose
omnivector-solutions/license-manager-simulator pull request #20
Opened 2022-03-29 22:52 UTC by julianaklulo

#### What
Add Dockerfile and docker-compose to lm-sim.

#### Why
We need a repeatable way to run the project.

`Task`: https://app.clickup.com/t/18022949/LM-183

---

#### Peer Review
Please follow the upstream omnivector documentation concerning
[peer-review guidelines](https://github.com/omnivector-solutions/Documentation/blob/main/Contributing/pr_review_standards.md#peer-review).

2022-03-30 12:44 UTC, heitorPB commented on Dockerfile
> +RUN apt update && apt install -y curl
```suggestion
RUN apt-get update && apt-get install -y curl
```

`apt` should not be used in scripts, on some situations it requests actions from the user with non-scriptable actions.

2022-03-30 12:46 UTC, heitorPB commented on Dockerfile
> +    ln -s /opt/poetry/bin/poetry && \
Why not this:

```suggestion
RUN pip install poetry && \
```

2022-03-30 12:48 UTC, heitorPB requested changes
Looks great! Just missing a `.dockerignore` with at least `.git` in it.

2022-03-30 18:42 UTC, jamesbeedy commented on Dockerfile
> +    ln -s /opt/poetry/bin/poetry && \
Do we even need poetry here?

2022-03-30 18:48 UTC, heitorPB commented on Dockerfile
> +    ln -s /opt/poetry/bin/poetry && \
I think it is OK to use Poetry to install the dependencies. This is for local development only, not for a production system.

2022-03-31 16:42 UTC, matheushent commented on Dockerfile
> +RUN apt update && apt install -y curl
I guess adding `ARG DEBIAN_FRONTEND=noninteractive` in the beginning of the file can overcome these situations, doesn't?

2022-03-31 20:28 UTC, julianaklulo commented on Dockerfile
> +    ln -s /opt/poetry/bin/poetry && \
I used the LM Dockerfile as a base for this one and we're installing poetry that way there as well. I tested installing it with pip and it worked, so I changed it in the latest commit.

2022-03-31 20:28 UTC, julianaklulo commented on docker-compose.yaml
> +    image: postgres
Sure, I changed it in the latest commit.

2022-03-31 20:33 UTC, julianaklulo commented
> Looks great! Just missing a `.dockerignore` with at least `.git` in it.

@heitorPB I added .dockerignore, can you review again please?

2022-03-31 20:55 UTC, heitorPB approved these changes
Nice work!

2022-03-31 21:07 UTC, merged